### ISSUE TITLE
What to do with archived repositories

### ISSUE THREAD

**Issue by jeroen** [ropensci/roregistry#26]
We are getting [build errors](http://jenkins.ropensci.org/blue/organizations/jenkins/siftgeojson/detail/siftgeojson/2/pipeline) for e.g.  `siftgeojson` because the github repository has been archived. However the package is still listed in the registry and is therefore picked up by jenkins.

Should we remove archived repositories from the registry? Or should the build server check the registry and skip projects with status _abandoned_ ?

@maelle @sckott @karthik

**Comment by maelle** [comment]
I think archives repos should be excluded from the registry.

**Comment by sckott** [comment]
> Should we remove archived repositories from the registry?

what does that mean exactly?  remove the repo from https://github.com/ropenscilabs/siftgeojson/ OR just don't include it in our generated registry json file?

**Comment by maelle** [comment]
Not including them in the json

**Comment by sckott** [comment]
Removing form the registry might be good - but did we have a previous conversation where maybe we wante to keep archived repos visible on the packages page in case someone sees it and wants to revive the pkg?

**Comment by karthik** [comment]
Might be a dumb idea but can we keep two registries? Or filter one down with a tag (abandoned etc) so that we build only on the good list but use the other for purposes described above (legacy reasons and the possibility that someone will resurrect tools?)

**Comment by maelle** [comment]
What version would be shown on ropensci.org/packages? Currently it shows all packages, by default only active ones but one can uncheck that box.

**Comment by maelle** [comment]
I'd be in favor of the registry containing all repos like it does now, but with an automatic abandoned status (added at registry building if the repo has to repostatus.org badge) if the repo is archived. The registry.json would contain an archived field, so Jenkings could filter them?

If that solution were to be chosen @sckott I'd need a text file with the list of archived repos that'd be created at the moment you pull repos from the orgs (because you could then check archived/not).

Archived repos at the moment seem to all have badges but in this case it is not a repostatus.org one https://github.com/ropenscilabs/webrockets

**Comment by maelle** [comment]
@jeroen furthermore, if we go with this solution I'd give you a list of the statuses to exclude, since it might be "suspended" as well as "abandoned" for instance.

**Comment by maelle** [comment]
ropenscilabs/webrockets is an archived repo.

**Comment by maelle** [comment]
outdated
