### ISSUE TITLE
repostatus badge not up to date with what repo has

### ISSUE THREAD

**Issue by sckott** [ropensci/roregistry#29]
`citesdb` is on our pkgs page at https://ropensci.org/packages/ - but you have to unclick "active repos" to show it. 

in its github repo it has an **Active** status badge - presumably at some point it had a WIP badge

not sure what's going on here

**Comment by maelle** [comment]
I'll clone citesdb and have a look. I'm nearly sure it's because the codemeta.json building fails for it so the entry isn't updated. Should we edit the script to dump names of packages for which there was a failure? At the moment their names are printed to screen.

https://github.com/ropenscilabs/makeregistry/blob/cfe283a6d52131fac9fe41d97a6aa884ba8c6d6d/R/codemeta.R#L14

**Comment by maelle** [comment]
found the issue in codemetar, will work on a fix. 

Issue = even when `force_update` is TRUE, the status is only replaced if it was not NULL.

**Comment by maelle** [comment]
https://github.com/ropensci/codemetar/pull/249

**Comment by maelle** [comment]
it seems fine now, thanks again for the bug report.
