### ISSUE TITLE
URLs: maybe add more

### ISSUE THREAD

**Issue by sckott** [ropensci/roregistry#8]
for 

- rendered pkgdown site or similar?
- vignette on cran?
- other?

**Comment by maelle** [comment]
"rendered pkgdown site or similar?" 👍 

other: tutorial page (maybe OpenCPU tutorial page)

**Comment by sckott** [comment]
Good idea.

**Comment by maelle** [comment]
RTD if https://github.com/ropensci/onboarding-meta/issues/28#issuecomment-364785685

**Comment by maelle** [comment]
With `codemetar` now in relatedLinks one gets:

* the URL(s) from DESCRIPTION that are listed under URL and are not the codeRepository (so if you have both your GitHub repo and pkgdown website like this https://github.com/ropensci/codemetar/blob/master/DESCRIPTION#L41 you get the pkgdown website. So I guess we should encourage developers to use the URL DESCRIPTION field with all their links.

* If the provider is CRAN or BioConductor (checked via the name of the package, and to get a confirmation we look whether there is a README badge which we should encourage -- otherwise you could call your package `crul` without its being the CRAN `crul`/if codemeta is built from an installed package we check the install source)

I guess it means we do not have the vignettes links. In theory one could scrape CRAN page and get them (or from metacran etc, I don't know). Would it make sense or is the CRAN canonical (of course) URL enough?

**Comment by maelle** [comment]
Other URL I've thought about adding https://github.com/ropensci/codemetar/issues/82

**Comment by maelle** [comment]
Closing this, if one stores the raw CodeMeta, one has more URLs than ever needed. :wink:
